# Generated by Django 5.0.6 on 2024-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_course_preview_alter_lesson_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10000, verbose_name='Цена курса'),
        ),
    ]
