# Generated by Django 5.0.6 on 2024-06-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
    ]
