# Generated by Django 5.0.6 on 2024-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма платежа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='идентификатор платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
